### ISSUE TITLE
How is this open source?

### ISSUE THREAD

**Issue by brannondorsey** [CloakProject/2.1.0.0-Wallets#14]
How can Cloak Coin claim to be open source when the only wallets available are provided as binaries? Am I missing something?

**Comment by cloak-design** [comment]
For open source please see https://github.com/CloakProject/Cloak2Public

If you have any problems, please open an issue under the repo link above.

Thanks

**Comment by fradow-cloak** [comment]
I added a link in the readme to avoid confusion in the future. Closing.

**Comment by brannondorsey** [comment]
Thank you for clearing this up :+1:
