### ISSUE TITLE
debug.log getting filled rapidly with "unknown message=ann9"

### ISSUE THREAD

**Issue by CryptoSiD** [CloakProject/2.1.0.0-Wallets#9]
I've synced the daemon on my server and now that the sync is complete the wallet still consume 60% of the cpu.

The debug.log is getting filled with the following, at about 100 lines per second.

unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.
unknown message=ann9.

Seeking for a solution.

**Comment by cloak-design** [comment]
If you still have an issue with the install please speak to the team in the wallet channel on chat.cloakcoin.com.

This is an isolated issue with the install.
